nodes = require("nodes")
functionName = nodes.referenceNode()
functionName.reference = "hasCake"
myFunction = nodes.functionNode()
myFunction.addArgument("is_a_lie")
assignName = nodes.assingNode()
toAssignPlug = assignName.addToAssign()
toAssignPlug.connect(functionName.plugs["reference"])
assignName.plugs["value_or_ref"].connect(myFunction.plugs["value"])
returnNode = nodes.returnNode()
toReturnPlug = returnNode.addToReturn()
toReturnPlug.connect(myFunction.plugs["is_a_lie"])
myFunction.plugs["body"].connect(returnNode.plugs["before"])
print(assignName.plugs["before"].getTextRepresentation())